# Generated by Django 5.0.6 on 2025-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Groceries', 'Groceries'), ('Books', 'Books'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
